# Generated by Django 3.1.7 on 2021-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PhotoAlbum', '0004_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
