# Generated by Django 3.1.7 on 2021-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoAlbum', '0006_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='probability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
